site_name: avaread
site_description: A project for reading spectra from Avantes AvaSoft files in python
site_author: Antoine Salden
site_url: https://github.com/AntoineTUE/avaread
copyright: 'Copyright &copy; Antoine Salden 2025-present'
repo_name: avaread
repo_url: https://github.com/AntoineTUE/avaread
docs_dir: docs
site_dir: site

watch:
  - src/avaread
  - docs

nav:
  - Home: index.md
  - Examples: examples.ipynb
  - API Reference
  - License: license.md

theme:
  name: material
  language: en
  icon:
    repo: fontawesome/brands/github-alt
    logo: material/book-open
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
  features:
    - navigation.footer
    - navigation.sections
    - toc.follow
    - content.code.copy

plugins:
  search: {}
  autorefs: {}
  include-markdown: {}
  gh-admonitions: {}
  mike:
    alias_type: symlink
    canonical_version: dev
  git-revision-date-localized:
    exclude:
      - reference/*
    fallback_to_build_date: true
    enable_creation_date: true
  api-autonav:
    modules: ['src/avaread']
    nav_section_title: API Reference
    # module_options:
    #   avaread.AvaTypes:

  section-index: {}
  mkdocstrings:
    default_handler: python_xref
    handlers:
      python_xref:
        paths:
          - src
        inventories:
          - https://numpy.org/doc/stable/objects.inv
        options:
          members_order: source
          relative_crossrefs: true
          docstring_style: google
          docstring_options:
            ignore_init_summary: yes
          filters:
            - "!^__"
          summary: true
          merge_init_into_class: yes
          show_submodules: no
          show_root_heading: false
          show_root_full_path: true
          show_root_members_full_path: false
          show_if_no_docstring: true
          show_docstring_modules: true
          show_docstring_attributes: true
          show_docstring_functions: true
          annotations_path: brief
          separate_signature: true
          signature_crossrefs: true
          line_length: 120
          show_signature_annotations: true
          show_bases: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          show_labels: false
          show_attribute_values: true
          extra:
            show_docstrings_modules: true
  mkdocs-jupyter:
    include_requirejs: true
    include_source: true
    include: ["*.ipynb"]
    ignore: ["*/.ipynb_checkpoints/*.ipynb"]

markdown_extensions:
  - markdown.extensions.abbr:
  - markdown.extensions.admonition:
  - markdown.extensions.attr_list:
  - markdown.extensions.footnotes:
  - markdown.extensions.meta:
  - markdown.extensions.tables:
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex:
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret:
  - pymdownx.critic:
  - pymdownx.details:
  - pymdownx.highlight:
      guess_lang: false
      linenums_style: pymdownx-inline
      use_pygments: true
  - pymdownx.inlinehilite:
  - pymdownx.keys:
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shortener: true
      social_url_shorthand: true
      normalize_issue_symbols: true
      provider: github
      user: AntoineTUE
      repo: avaread
  - pymdownx.mark:
  - pymdownx.progressbar:
  - pymdownx.saneheaders:
  - pymdownx.smartsymbols:
  - pymdownx.superfences:
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde:

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/AntoineTUE/avaread

extra_javascript:
  - assets/javascript/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.min.js

extra_css:
  - assets/stylesheets/mkdocstrings.css
